document.writeln("<table width=\"758\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("  <form method=\"post\" name=\"login\" action=\"http:\/\/bbs.cooledu.com.cn\/logging.php?action=login\" target=\"_blank\">");
document.writeln("    <input type=\"hidden\" name=\"formhash\" value=\"6a49b97f\">");
document.writeln("    <input type=\"hidden\" name=\"referer\" value=\"index.php\">");
document.writeln("    <tr>");
document.writeln("      <td height=\"26\"><a href=\"http:\/\/bbs.cooledu.com.cn\/\" target=\"_blank\"><img src=\"\/images\/catchword.gif\" alt=\"教育成就未来!\" width=\"183\" height=\"26\" hspace=\"3\" border=\"0\" \/><\/a><\/td>");
document.writeln("      <td width=\"52\">用户名：<\/td>");
document.writeln("      <td width=\"116\"><input name=\"username\" type=\"text\" maxlength=\"40\" class=\"topinput\"><\/td>");
document.writeln("      <td width=\"40\">密码：<\/td>");
document.writeln("      <td width=\"116\"><input name=\"password\" type=\"password\" class=\"topinput\"><\/td>");
document.writeln("      <td width=\"60\"><input name=\"loginsubmit\" type=\"submit\" class=\"loginenter\" value=\"登 陆\"><\/td>");
document.writeln("      <td width=\"60\"><a href=\"http:\/\/bbs.cooledu.com.cn\/register.php\" target=\"_blank\"><img src=\"\/images\/coolreg.gif\" width=\"45\" height=\"18\" border=\"0\"><\/a><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/form>");
document.writeln("<\/table>");