document.writeln("<script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"pub-4256750528022331\";");
document.writeln("google_ad_width = 468;");
document.writeln("google_ad_height = 60;");
document.writeln("google_ad_format = \"468x60_as_rimg\";");
document.writeln("google_cpa_choice = \"CAAQ3LXUlAIaCNElPYPmEcvKKLj39IMB\";");
document.writeln("google_ad_channel = \"5132753251\";");
document.writeln("\/\/--><\/script>");
document.writeln("<script type=\"text\/javascript\" src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");